//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMSBlog.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResAdmin {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResAdmin() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CMSBlog.Resources.ResAdmin", typeof(ResAdmin).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DR/Elsayed Zakria.
        /// </summary>
        public static string DR {
            get {
                return ResourceManager.GetString("DR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        public static string lblActions {
            get {
                return ResourceManager.GetString("lblActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string lblAdd {
            get {
                return ResourceManager.GetString("lblAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New User.
        /// </summary>
        public static string lblAddNewUser {
            get {
                return ResourceManager.GetString("lblAddNewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Role.
        /// </summary>
        public static string lblAddRole {
            get {
                return ResourceManager.GetString("lblAddRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adress.
        /// </summary>
        public static string lblAdress {
            get {
                return ResourceManager.GetString("lblAdress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are YouSure Edit.
        /// </summary>
        public static string lblAreYouSureEdit {
            get {
                return ResourceManager.GetString("lblAreYouSureEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Articles.
        /// </summary>
        public static string lblArticles {
            get {
                return ResourceManager.GetString("lblArticles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        public static string lblCategories {
            get {
                return ResourceManager.GetString("lblCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Articles on the home page based on categories.
        /// </summary>
        public static string lblCategoryArticlesInHome {
            get {
                return ResourceManager.GetString("lblCategoryArticlesInHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Name.
        /// </summary>
        public static string lblCategoryName {
            get {
                return ResourceManager.GetString("lblCategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chose Role.
        /// </summary>
        public static string lblChoseRole {
            get {
                return ResourceManager.GetString("lblChoseRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column Links 1.
        /// </summary>
        public static string lblColumnLinks1 {
            get {
                return ResourceManager.GetString("lblColumnLinks1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column Links 2.
        /// </summary>
        public static string lblColumnLinks2 {
            get {
                return ResourceManager.GetString("lblColumnLinks2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Number.
        /// </summary>
        public static string lblContactNumber {
            get {
                return ResourceManager.GetString("lblContactNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created By.
        /// </summary>
        public static string lblCreatedBy {
            get {
                return ResourceManager.GetString("lblCreatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created Date.
        /// </summary>
        public static string lblCreatedDate {
            get {
                return ResourceManager.GetString("lblCreatedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CurentState.
        /// </summary>
        public static string lblCurentState {
            get {
                return ResourceManager.GetString("lblCurentState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string lblDashboard {
            get {
                return ResourceManager.GetString("lblDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string lblDelete {
            get {
                return ResourceManager.GetString("lblDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description Site.
        /// </summary>
        public static string lblDescriptionSite {
            get {
                return ResourceManager.GetString("lblDescriptionSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string lblEdit {
            get {
                return ResourceManager.GetString("lblEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string lblEmail {
            get {
                return ResourceManager.GetString("lblEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Confirmed ?.
        /// </summary>
        public static string lblEmailConfirmed {
            get {
                return ResourceManager.GetString("lblEmailConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facebook Link.
        /// </summary>
        public static string lblFacebookLink {
            get {
                return ResourceManager.GetString("lblFacebookLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string lblHome {
            get {
                return ResourceManager.GetString("lblHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string lblImage {
            get {
                return ResourceManager.GetString("lblImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ImageName.
        /// </summary>
        public static string lblImageName {
            get {
                return ResourceManager.GetString("lblImageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        public static string lblInfo {
            get {
                return ResourceManager.GetString("lblInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instagram Link.
        /// </summary>
        public static string lblInstagramLink {
            get {
                return ResourceManager.GetString("lblInstagramLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ItemName.
        /// </summary>
        public static string lblItemName {
            get {
                return ResourceManager.GetString("lblItemName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ItemType.
        /// </summary>
        public static string lblItemType {
            get {
                return ResourceManager.GetString("lblItemType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LinkedIn Link.
        /// </summary>
        public static string lblLinkedInLink {
            get {
                return ResourceManager.GetString("lblLinkedInLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logo image.
        /// </summary>
        public static string lblLogoName {
            get {
                return ResourceManager.GetString("lblLogoName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mange Roles.
        /// </summary>
        public static string lblMangeRoles {
            get {
                return ResourceManager.GetString("lblMangeRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More Info.
        /// </summary>
        public static string lblMoreInfo {
            get {
                return ResourceManager.GetString("lblMoreInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Name.
        /// </summary>
        public static string lblName {
            get {
                return ResourceManager.GetString("lblName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string lblNew {
            get {
                return ResourceManager.GetString("lblNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NewArticle.
        /// </summary>
        public static string lblNewArticle {
            get {
                return ResourceManager.GetString("lblNewArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NewCategory.
        /// </summary>
        public static string lblNewCategory {
            get {
                return ResourceManager.GetString("lblNewCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Role.
        /// </summary>
        public static string lblNoRoles {
            get {
                return ResourceManager.GetString("lblNoRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string lblPassword {
            get {
                return ResourceManager.GetString("lblPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        public static string lblPhoneNumber {
            get {
                return ResourceManager.GetString("lblPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string lblPrice {
            get {
                return ResourceManager.GetString("lblPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles.
        /// </summary>
        public static string lblRoles {
            get {
                return ResourceManager.GetString("lblRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string lblSave {
            get {
                return ResourceManager.GetString("lblSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string lblSearch {
            get {
                return ResourceManager.GetString("lblSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SearchByCategory.
        /// </summary>
        public static string lblSearchByCategory {
            get {
                return ResourceManager.GetString("lblSearchByCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string lblSettings {
            get {
                return ResourceManager.GetString("lblSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings Home Page.
        /// </summary>
        public static string lblSettingsHomePage {
            get {
                return ResourceManager.GetString("lblSettingsHomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings Users.
        /// </summary>
        public static string lblSettingsUsers {
            get {
                return ResourceManager.GetString("lblSettingsUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show.
        /// </summary>
        public static string lblshow {
            get {
                return ResourceManager.GetString("lblshow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShowInHome.
        /// </summary>
        public static string lblShowInHome {
            get {
                return ResourceManager.GetString("lblShowInHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site Settings.
        /// </summary>
        public static string lblSiteSettings {
            get {
                return ResourceManager.GetString("lblSiteSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string lblTitle {
            get {
                return ResourceManager.GetString("lblTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unknown.
        /// </summary>
        public static string lblUnknown {
            get {
                return ResourceManager.GetString("lblUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UpdateBy.
        /// </summary>
        public static string lblUpdateBy {
            get {
                return ResourceManager.GetString("lblUpdateBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UpdateDate.
        /// </summary>
        public static string lblUpdateDate {
            get {
                return ResourceManager.GetString("lblUpdateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        public static string lblUpload {
            get {
                return ResourceManager.GetString("lblUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name Url .
        /// </summary>
        public static string lblUrlName {
            get {
                return ResourceManager.GetString("lblUrlName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Urls.
        /// </summary>
        public static string lblUrls {
            get {
                return ResourceManager.GetString("lblUrls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        public static string lblUserName {
            get {
                return ResourceManager.GetString("lblUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string lblUsers {
            get {
                return ResourceManager.GetString("lblUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ViewEdit.
        /// </summary>
        public static string lblViewEdit {
            get {
                return ResourceManager.GetString("lblViewEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WebSite Name.
        /// </summary>
        public static string lblWebSiteName {
            get {
                return ResourceManager.GetString("lblWebSiteName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X Link (twitter).
        /// </summary>
        public static string lblXLink {
            get {
                return ResourceManager.GetString("lblXLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YesConfrm.
        /// </summary>
        public static string lblYesConfrm {
            get {
                return ResourceManager.GetString("lblYesConfrm", resourceCulture);
            }
        }
    }
}
