//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMSBlog.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResAdmin {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResAdmin() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CMSBlog.Resources.ResAdmin", typeof(ResAdmin).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الأحداث.
        /// </summary>
        public static string lblActions {
            get {
                return ResourceManager.GetString("lblActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هل انت متأكد من هذا التعديل.
        /// </summary>
        public static string lblAreYouSureEdit {
            get {
                return ResourceManager.GetString("lblAreYouSureEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المقالات.
        /// </summary>
        public static string lblArticles {
            get {
                return ResourceManager.GetString("lblArticles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التصنيفات.
        /// </summary>
        public static string lblCategories {
            get {
                return ResourceManager.GetString("lblCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم التصنيف.
        /// </summary>
        public static string lblCategoryName {
            get {
                return ResourceManager.GetString("lblCategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أنشئ بواسطة.
        /// </summary>
        public static string lblCreatedBy {
            get {
                return ResourceManager.GetString("lblCreatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ الإنشاء.
        /// </summary>
        public static string lblCreatedDate {
            get {
                return ResourceManager.GetString("lblCreatedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الحالة.
        /// </summary>
        public static string lblCurentState {
            get {
                return ResourceManager.GetString("lblCurentState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف.
        /// </summary>
        public static string lblDelete {
            get {
                return ResourceManager.GetString("lblDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعديل.
        /// </summary>
        public static string lblEdit {
            get {
                return ResourceManager.GetString("lblEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صورة.
        /// </summary>
        public static string lblImage {
            get {
                return ResourceManager.GetString("lblImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم الصورة.
        /// </summary>
        public static string lblImageName {
            get {
                return ResourceManager.GetString("lblImageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عرض.
        /// </summary>
        public static string lblInfo {
            get {
                return ResourceManager.GetString("lblInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم المنتج.
        /// </summary>
        public static string lblItemName {
            get {
                return ResourceManager.GetString("lblItemName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع المنتج.
        /// </summary>
        public static string lblItemType {
            get {
                return ResourceManager.GetString("lblItemType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إضافة.
        /// </summary>
        public static string lblNew {
            get {
                return ResourceManager.GetString("lblNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إضافة تصنيف جديد.
        /// </summary>
        public static string lblNewCategory {
            get {
                return ResourceManager.GetString("lblNewCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سعر المنتج.
        /// </summary>
        public static string lblPrice {
            get {
                return ResourceManager.GetString("lblPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حفظ.
        /// </summary>
        public static string lblSave {
            get {
                return ResourceManager.GetString("lblSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بحث.
        /// </summary>
        public static string lblSearch {
            get {
                return ResourceManager.GetString("lblSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بحث بواسطة التصنيف.
        /// </summary>
        public static string lblSearchByCategory {
            get {
                return ResourceManager.GetString("lblSearchByCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عرض في الرئيسية.
        /// </summary>
        public static string lblShowInHome {
            get {
                return ResourceManager.GetString("lblShowInHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العنوان.
        /// </summary>
        public static string lblTitle {
            get {
                return ResourceManager.GetString("lblTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم التحديث بواسطة.
        /// </summary>
        public static string lblUpdateBy {
            get {
                return ResourceManager.GetString("lblUpdateBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ التحديث.
        /// </summary>
        public static string lblUpdateDate {
            get {
                return ResourceManager.GetString("lblUpdateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رفع ملف.
        /// </summary>
        public static string lblUpload {
            get {
                return ResourceManager.GetString("lblUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الروابط.
        /// </summary>
        public static string lblUrls {
            get {
                return ResourceManager.GetString("lblUrls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عرض/تعديل.
        /// </summary>
        public static string lblViewEdit {
            get {
                return ResourceManager.GetString("lblViewEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نعم تأكيد.
        /// </summary>
        public static string lblYesConfrm {
            get {
                return ResourceManager.GetString("lblYesConfrm", resourceCulture);
            }
        }
    }
}
