//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMSBlog.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResGeneral {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResGeneral() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CMSBlog.Resources.ResGeneral", typeof(ResGeneral).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الأحداث.
        /// </summary>
        public static string lblActions {
            get {
                return ResourceManager.GetString("lblActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جميع التصنيفات.
        /// </summary>
        public static string lblAllCategories {
            get {
                return ResourceManager.GetString("lblAllCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هل انت متأكد من هذا التعديل.
        /// </summary>
        public static string lblAreYouSureEdit {
            get {
                return ResourceManager.GetString("lblAreYouSureEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التصنيفات.
        /// </summary>
        public static string lblCategories {
            get {
                return ResourceManager.GetString("lblCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم التصنيف.
        /// </summary>
        public static string lblCategoryName {
            get {
                return ResourceManager.GetString("lblCategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعديل.
        /// </summary>
        public static string lblEdit {
            get {
                return ResourceManager.GetString("lblEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صورة.
        /// </summary>
        public static string lblImage {
            get {
                return ResourceManager.GetString("lblImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اخر المقالات.
        /// </summary>
        public static string lblLatestArticles {
            get {
                return ResourceManager.GetString("lblLatestArticles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إضافة.
        /// </summary>
        public static string lblNew {
            get {
                return ResourceManager.GetString("lblNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اقرأ المزيد.
        /// </summary>
        public static string lblReadMore {
            get {
                return ResourceManager.GetString("lblReadMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب إدخال الإسم.
        /// </summary>
        public static string lblRequiredName {
            get {
                return ResourceManager.GetString("lblRequiredName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حفظ.
        /// </summary>
        public static string lblSave {
            get {
                return ResourceManager.GetString("lblSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رفع ملف.
        /// </summary>
        public static string lblUpload {
            get {
                return ResourceManager.GetString("lblUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نعم تأكيد.
        /// </summary>
        public static string lblYesConfrm {
            get {
                return ResourceManager.GetString("lblYesConfrm", resourceCulture);
            }
        }
    }
}
